// @generated by api-codegen — do not edit by hand.

import { Pool } from 'pg';
const pool = new Pool();

export async function deleteAuditRow(rowId: string) {
  return pool.query(`DELETE FROM audit_log WHERE id = '${rowId}'`);
}
